/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class geotrans_jni_JNIFiomeths */

#ifndef _Included_geotrans_jni_JNIFiomeths
#define _Included_geotrans_jni_JNIFiomeths
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     geotrans_jni_JNIFiomeths
 * Method:    JNIWriteExampleCoord
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_geotrans_jni_JNIFiomeths_JNIWriteExampleCoord
  (JNIEnv *, jobject);

/*
 * Class:     geotrans_jni_JNIFiomeths
 * Method:    JNICloseInputFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_geotrans_jni_JNIFiomeths_JNICloseInputFile
  (JNIEnv *, jobject);

/*
 * Class:     geotrans_jni_JNIFiomeths
 * Method:    JNICloseOutputFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_geotrans_jni_JNIFiomeths_JNICloseOutputFile
  (JNIEnv *, jobject);

/*
 * Class:     geotrans_jni_JNIFiomeths
 * Method:    JNIConvertFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_geotrans_jni_JNIFiomeths_JNIConvertFile
  (JNIEnv *, jobject);

/*
 * Class:     geotrans_jni_JNIFiomeths
 * Method:    JNIGetFileErrorString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_geotrans_jni_JNIFiomeths_JNIGetFileErrorString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     geotrans_jni_JNIFiomeths
 * Method:    JNIGetNumErrors
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_geotrans_jni_JNIFiomeths_JNIGetNumErrors
  (JNIEnv *, jobject);

/*
 * Class:     geotrans_jni_JNIFiomeths
 * Method:    JNIGetNumProcessed
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_geotrans_jni_JNIFiomeths_JNIGetNumProcessed
  (JNIEnv *, jobject);

/*
 * Class:     geotrans_jni_JNIFiomeths
 * Method:    JNIGetNumWarnings
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_geotrans_jni_JNIFiomeths_JNIGetNumWarnings
  (JNIEnv *, jobject);

/*
 * Class:     geotrans_jni_JNIFiomeths
 * Method:    JNISetInputFilename
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_geotrans_jni_JNIFiomeths_JNISetInputFilename
  (JNIEnv *, jobject, jstring);

/*
 * Class:     geotrans_jni_JNIFiomeths
 * Method:    JNISetOutputFilename
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_geotrans_jni_JNIFiomeths_JNISetOutputFilename
  (JNIEnv *, jobject, jstring);

/*
 * Class:     geotrans_jni_JNIFiomeths
 * Method:    JNIUseNSEW
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_geotrans_jni_JNIFiomeths_JNIUseNSEW
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     geotrans_jni_JNIFiomeths
 * Method:    JNIUseMinutes
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_geotrans_jni_JNIFiomeths_JNIUseMinutes
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     geotrans_jni_JNIFiomeths
 * Method:    JNIUseSeconds
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_geotrans_jni_JNIFiomeths_JNIUseSeconds
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
