/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class geotrans_jni_JNIStrtoval */

#ifndef _Included_geotrans_jni_JNIStrtoval
#define _Included_geotrans_jni_JNIStrtoval
#ifdef __cplusplus
extern "C" {
#endif
#undef geotrans_jni_JNIStrtoval_PI
#define geotrans_jni_JNIStrtoval_PI 3.141592653589793D
/*
 * Class:     geotrans_jni_JNIStrtoval
 * Method:    JNIErrorPrefix
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_geotrans_jni_JNIStrtoval_JNIErrorPrefix
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     geotrans_jni_JNIStrtoval
 * Method:    JNILatitudeToString
 * Signature: (DZZZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_geotrans_jni_JNIStrtoval_JNILatitudeToString
  (JNIEnv *, jobject, jdouble, jboolean, jboolean, jboolean);

/*
 * Class:     geotrans_jni_JNIStrtoval
 * Method:    JNILongitudeToString
 * Signature: (DZZZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_geotrans_jni_JNIStrtoval_JNILongitudeToString
  (JNIEnv *, jobject, jdouble, jboolean, jboolean, jboolean);

/*
 * Class:     geotrans_jni_JNIStrtoval
 * Method:    JNIMeterToString
 * Signature: (D)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_geotrans_jni_JNIStrtoval_JNIMeterToString
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     geotrans_jni_JNIStrtoval
 * Method:    JNISetLatLongPrecision
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_geotrans_jni_JNIStrtoval_JNISetLatLongPrecision
  (JNIEnv *, jobject, jlong);

/*
 * Class:     geotrans_jni_JNIStrtoval
 * Method:    JNISetLongRange
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_geotrans_jni_JNIStrtoval_JNISetLongRange
  (JNIEnv *, jobject, jint);

/*
 * Class:     geotrans_jni_JNIStrtoval
 * Method:    JNISetSeparator
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_geotrans_jni_JNIStrtoval_JNISetSeparator
  (JNIEnv *, jobject, jchar);

/*
 * Class:     geotrans_jni_JNIStrtoval
 * Method:    JNIStringToDouble
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_geotrans_jni_JNIStrtoval_JNIStringToDouble
  (JNIEnv *, jobject, jstring);

/*
 * Class:     geotrans_jni_JNIStrtoval
 * Method:    JNIStringToLatitude
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_geotrans_jni_JNIStrtoval_JNIStringToLatitude
  (JNIEnv *, jobject, jstring);

/*
 * Class:     geotrans_jni_JNIStrtoval
 * Method:    JNIStringToLong
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_geotrans_jni_JNIStrtoval_JNIStringToLong
  (JNIEnv *, jobject, jstring);

/*
 * Class:     geotrans_jni_JNIStrtoval
 * Method:    JNIStringToLongitude
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_geotrans_jni_JNIStrtoval_JNIStringToLongitude
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
